#define minimumPriorityThreshold 1
#define appDelegatePriority 1
#define contactManagerPriority 2
#define urgencyCalculatorPriority 2
#define mainViewControllerPriority 3
#define contactViewControllerPriority 3
#define helpViewControllerPriority 1
#define settingsTableViewControllerPriority 1
#define allContactsTableViewControllerPriority 2
#define contactInformationTableViewControllerPriority 2
#define contactCardViewPriority 3
#define facebookManagerPriority 3